<?php

use Drupal\file\Entity\File;
use Drupal\menu_link_content\Entity\MenuLinkContent;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;
use Drupal\user\Entity\User;

// ========== theme functions start ==========
function hello_theme($existing, $type, $theme, $path)
{
//    $log = "existing=". json_encode($existing);
//    $log .= "||type=" . json_encode($type);
//    $log .= "||theme=" . json_encode($theme);
//    $log .= "||path=" . json_encode($path);
//    \Drupal::logger("hello_theme")->info($log);
    return array(
        'sayhello' => array(
            'variables' => array(
                'test1' => null,
                'markup'=>null,
            ),
        ),
    );
}

function template_preprocess_sayhello(&$variables){
    \Drupal::logger("hello_theme_preprocess")->info(json_encode($variables));
}
// ========== theme functions end ==========

function hello_hello_world()
{
    \Drupal::logger("hello")->info("in hello.sayhello in hello.module");
    return t('Hello Drupal 8 World!');
}

function hello_welcome()
{
    $user = User::load(\Drupal::currentUser()->id());
    if ($user->get('uid')->value < 1) {
        return t('Welcome  Visitor!');
    } else {
        return t('Welcome  ' . $user->getUsername() . '!');
    }
}

function hello_create_node()
{
    $node = Node::create([
        // The node entity bundle.
        'type' => 'article',
        'langcode' => 'en',
        'created' => \Drupal::time()->getRequestTime(),
        'changed' => \Drupal::time()->getRequestTime(),
        // The user ID.
        'uid' => 1,
        'title' => 'My test!',
        // An array with taxonomy terms.
        'field_tags' => [1],
        'body' => [
            'summary' => '',
            'value' => '<p>The body of my node.</p>',
            'format' => 'full_html',
        ],]);
    $node->save();
//    \Drupal::service('path.alias_storage')->save("/node/" . $node->id(), "/hello/example-node", "en");
//    $node_es = $node->addTranslation('es');
//    $node_es->title = 'Mi prueba!';
//    $node_es->body->value = '<p>El cuerpo de mi nodo.</p>';
//    $node_es->body->format = 'full_html';
//    $node_es->save();
//    \Drupal::service('path.alias_storage')->save("/node/" . $node->id(), "/mi/ruta", "es");
    return t("Created node " . $node->get('title')->value);
}

function hello_create_file()
{
    // create a new function and place this code in the function
    $file = File::create([
        'uid' => 1,
        'filename' => 'lu.svg',
        'uri' => 'public://lu.svg',
        'status' => 1,
    ]);
    $file->save();
    return t("File was successfully created");
}

function hello_add_taxonomy_term()
{
    $term = Term::create([
        'vid' => 'tags',
        'langcode' => 'en',
        'name' => 'My tag',
        'description' => [
            'value' => '<p>My description.</p>',
            'format' => 'full_html',
        ],
        'weight' => -1,
        'parent' => array(0),
    ]);
    $term->save();
    return t('The term was successfully created');
}

function hello_create_menu_link()
{
    // the code that should be implemented in a function to create a menu item
    $menu_item = MenuLinkContent::create([
        'bundle' => 'menu_link_content',
        'langcode' => 'en',
        'title' => 'My menu link',
        'description' => 'My description.',
        'menu_name' => 'main',
        'link' => [['uri' => 'internal:/node/1']],
        'weight' => 0,
    ]);
    $menu_item->save();
    return t('The menu link was successfully created');
}